### ISSUE TITLE
ユースケース「システム管理コンソールへログインする」の実装中に気がついた一般ユーザ操作系のリファクタリングポイントに対処する

### ISSUE THREAD

**Issue by clap-and-whistle** [clap-and-whistle/spring-boot-demo#19]
# 対応の概要

- [x] UserAggregateRepositoryクラスのisPasswordMatch()メソッドの実装箇所を変更
    - [x] ついでに、同ファイル中の Optional を使ってない系の警告箇所も潰しておく。
- [x] 各種Controllerの持つ各種Actionメソッドにて、templateパスをreturnする際の記述書式を統一する
    - [x] ついでに、編集対象コントローラ中にIDEからの警告などがあれば極力直す
    - [x] ついでに、templateファイルにURLパスをベタ書きしてある箇所で変数へ置き換え可能なものがあれば直しておく。
- [x] ビジネスロジック層に紛れ込んでいるSpringアノテーションを除去する
- [x] src/main/java/配下にある単体テスト用のクラスを src/test/java/配下へ移す
- [x] 例外クラスの配置を見直す
    - [x] ビジネスロジック層で使用する例外クラスの内、 infra層へ配置されている例外クラスをビジネスロジック層へ移す
    - [x] ビジネスロジック層内でのパスワード系例外を、個別の集約単位ではなくRegistrationProcessFailedExceptionと同じ階層へ移す
- [x] 設計資料の手直しが必要な箇所の対処をする

# staging環境で入念にチェックする項目

- [x] ユースケース「アカウント作成の申請をする」において、postデータを処理してリダイレクトする際の遷移先が /demo/配下になっていることを確認する。

**Comment by Kimita** [comment]
devブランチへのマージとstaging環境での動作確認を完了したのでクローズ
